{{- if (not .Values.frontend.S3.bucket) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-uploads-claim
  namespace: {{ .Release.Namespace }}
  annotations: {{ .Values.persistence.annotations }}
spec:
{{- if (and .Values.persistence .Values.persistence.storageClassName) }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.frontend.volumes.uploads.size }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-data-claim
  namespace: {{ .Release.Namespace }}
  annotations: {{ .Values.persistence.annotations }}
spec:
{{- if (and .Values.persistence .Values.persistence.storageClassName) }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.image.volumes.data.size }}
