---
dependencies:
- name: cert-manager
  version: "0.15.1"
  repository: "https://charts.jetstack.io"
  condition: dependencies.cert-manager.enabled

- name: mongodb
  version: "7.14.5"
  repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
  condition: dependencies.mongodb.enabled
  image:
    ## Bitnami MongoDB registry
    ##
    registry: docker.io
    ## Bitnami MongoDB image name
    ##
    repository: bitnami/mongodb
    ## Bitnami MongoDB image tag
    ## ref: https://hub.docker.com/r/bitnami/mongodb/tags/
    ##
    tag: 4.0.14-ol-7-r39

- name: mysql
  version: "6.14.2"
  repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
  condition: dependencies.mysql.enabled
