apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailcatcher
  namespace: mailcatcher
  labels:
    k8s-app: mailcatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailcatcher
  template:
    metadata:
      labels:
        app: mailcatcher
    spec:
      containers:
        - name: mailcatcher
          image: dockage/mailcatcher:0.7.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          ports:
            - containerPort: 1080
              name: http
              protocol: TCP
            - containerPort: 1025
              name: mail
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: mailcatcher
  namespace: mailcatcher
spec:
  selector:
    app: mailcatcher
  ports:
    - name: http
      protocol: TCP
      port: 1080
    - name: smtp
      protocol: TCP
      port: 1025
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailcatcher
  namespace: mailcatcher
  annotations:
    # just a sample
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/16
spec:
  rules:
    - host: mailcatcher.wijikdemo.marviq.net
      http:
        paths:
          - backend:
              serviceName: mailcatcher
              servicePort: 1080
