---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  password: {{ .Values.secrets.mongodb.password | default "" | b64enc | quote }}
  frontend-connection-string: {{ .Values.secrets.mongodb.frontendConnectionString | default "" | b64enc | quote }}
  auth-connection-string: {{ .Values.secrets.mongodb.authConnectionString | default "" | replace "{database}" "sessions" | b64enc | quote }}
