---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-mongo-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  hostname: {{ .Values.secrets.mongodb.hostname | default (printf "%s-mongodb.%s.svc.cluster.local" .Release.Name .Release.Namespace) | b64enc }}
  hostport: {{ .Values.secrets.mongodb.hostport | default 27017 | toString | b64enc }}
  database: {{ .Values.secrets.mongodb.database | default "openstad_mongodb" | b64enc }}
  user: {{ .Values.secrets.mongodb.user | default "" | b64enc | quote }}
  auth-source: {{ .Values.secrets.mongodb.authSource | default "" | b64enc | quote }}
