frontend:
  deploymentContainer:
    image: openstad/frontend:v0.10.1
auth:
  deploymentContainer:
    image: openstad/auth:v0.10.0
admin:
  deploymentContainer:
    image: openstad/admin:v0.10.2
api:
  deploymentContainer:
    image: openstad/api:v0.10.0
image:
  deploymentContainer:
    image: openstad/image:v0.7.0

