frontend:
  deploymentContainer:
    image: savvycodes/openstad-frontend:feat-event-planner-dc0f870
auth:
  deploymentContainer:
    image: openstad/auth:v0.13.0
admin:
  deploymentContainer:
    image: openstad/admin:v0.13.0
api:
  deploymentContainer:
    image: savvycodes/openstad-api:feat-event-planner-2664d82
image:
  deploymentContainer:
    image: openstad/image:v0.7.0