frontend:
  deploymentContainer:
    image: savvycodes/openstad-frontend:feat-apostrophe-forms-3295db7
auth:
  deploymentContainer:
    image: openstad/auth:v0.16.0
admin:
  deploymentContainer:
    image: openstad/admin:v0.19.3-beta
api:
  deploymentContainer:
    image: savvycodes/openstad-api:release-1cac6ba
image:
  deploymentContainer:
    image: openstad/image:v0.7.0