frontend:
  deploymentContainer:
    image: savvycodes/openstad-frontend:feat-events-resource-page-ca1ad24
auth:
  deploymentContainer:
    image: openstad/auth:v0.41.0
admin:
  openstadReactAdminCdn: https://unpkg.com/@savvycodes/openstad-react-admin@alpha/dist
  deploymentContainer:
    image: openstad/admin:v0.41.0
api:
  deploymentContainer:
    image: savvycodes/openstad-api:fix-expired-events-69229f2
image:
  deploymentContainer:
    image: openstad/image:v0.40.0